### ISSUE TITLE
win10+docker RDP连接无法安装python3

### ISSUE THREAD

**Issue by GardenOfKruse** [danni-cool/wechatbotKit-py-http#1]
不知道如何处理下面场景，python3安装失败
![image](https://github.com/user-attachments/assets/d07a93b0-38f9-4d9f-9fd8-ca20242330d4)

环境：windows 10 + docker desktop 27.1.1  
python版本：python-3.12.6-amd64.exe、python-3.13.0rc2.exe  32位、64位都是相同错误
场景：拉取镜像，windows直接连接RDP，安装install的python setup报错

错误日志：
Unhandled exception: page fault on execute access to 0x0044b000 in wow64 32-bit code (0x0044b000).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:0044b000 ESP:0078ff54 EBP:0078ff68 EFLAGS:00010246(  R- --  I  Z- -P- )
 EAX:003f1000 EBX:003f1000 ECX:00000000 EDX:0042e082
 ESI:00000000 EDI:00000000
Stack dump:
0x0078ff54:  7b358b20 003f1000 7b505f03 7b505f03
0x0078ff64:  003f1000 0078ff80 7b505f03 003f1000
0x0078ff74:  00000000 00000000 00000000 0078ffec
0x0078ff84:  7b507375 7b358b10 0042e082 003f1000
0x0078ff94:  ffffffff 7b51bf40 7b4d3270 00000000
0x0078ffa4:  0078ffec 003f1000 00000000 00000000
Backtrace:
=>0 0x0044b000 in python-3.12.6-amd64 (+0x4b000) (0x0078ff68)
  1 0x7b505f03 in ntdll (+0x55f03) (0x0078ff80)
  2 0x7b507375 in ntdll (+0x57375) (0x0078ffec)
0x0044b000 python-3.12.6-amd64+0x4b000: les -0x32(%esi), %ebx
Modules:
Module  Address                 Debug info      Name (58 modules)
PE        400000-  489000       Export          python-3.12.6-amd64
PE-Wine 77e10000-77eb7000       Deferred        uxtheme
PE-Wine 77ed0000-77f1c000       Deferred        winex11
PE-Wine 77f30000-77f71000       Deferred        shcore
PE-Wine 77f90000-7807c000       Deferred        shlwapi
PE-Wine 78090000-780f3000       Deferred        imm32
PE-Wine 78110000-7858f000       Deferred        comctl32
PE-Wine 785a0000-785c1000       Deferred        aclui
PE-Wine 785e0000-792a5000       Deferred        shell32
PE-Wine 792c0000-79301000       Deferred        coml2
PE-Wine 79320000-79535000       Deferred        rpcrt4
PE-Wine 79550000-79695000       Deferred        combase
PE-Wine 796b0000-79af6000       Deferred        ole32
PE-Wine 79b10000-79ed7000       Deferred        oleaut32
PE-Wine 79ef0000-79f27000       Deferred        win32u
PE-Wine 79f40000-7a186000       Deferred        gdi32
PE      7a1a0000-7a1c8000       Deferred        zlib1
PE      7a1e0000-7a225000       Deferred        libpng16-16
PE-Wine 7a240000-7a64b000       Deferred        user32
PE-Wine 7a660000-7a974000       Deferred        ucrtbase
PE-Wine 7a990000-7aa1b000       Deferred        sechost
PE-Wine 7aa30000-7accf000       Deferred        msvcrt
PE-Wine 7ace0000-7adcd000       Deferred        advapi32
PE-Wine 7ade0000-7b317000       Deferred        kernelbase
PE-Wine 7b330000-7b49d000       Deferred        kernel32
PE-Wine 7b4b0000-7b7ae000       Dwarf-4-5       ntdll
ELF     7e2b2000-7e2ba000       Deferred        libxfixes.so.3
ELF     7e2ba000-7e2c7000       Deferred        libxcursor.so.1
ELF     7e2c7000-7e2db000       Deferred        libxi.so.6
ELF     7e2db000-7e2e0000       Deferred        libxcomposite.so.1
ELF     7e2e0000-7e2ef000       Deferred        libxrandr.so.2
ELF     7e2ef000-7e2fd000       Deferred        libxrender.so.1
ELF     7e2fd000-7e304000       Deferred        libxxf86vm.so.1
ELF     7e304000-7e309000       Deferred        libxinerama.so.1
ELF     7e309000-7e30f000       Deferred        libxau.so.6
ELF     7e30f000-7e33d000       Deferred        libxcb.so.1
ELF     7e33d000-7e494000       Deferred        libx11.so.6
ELF     7e494000-7e4ab000       Deferred        libxext.so.6
ELF     7e4b9000-7e540000       Deferred        winex11.so
ELF     7e558000-7e590000       Deferred        liblzma.so.5
ELF     7e590000-7e71c000       Deferred        libxml2.so.2
ELF     7e71c000-7e76e000       Deferred        libfontconfig.so.1
ELF     7e76e000-7e80a000       Deferred        libpcre2-8.so.0
ELF     7e80a000-7e82d000       Deferred        libbrotlicommon.so.1
ELF     7e82d000-7e84c000       Deferred        libgraphite2.so.3
ELF     7e84c000-7e9b8000       Deferred        libglib-2.0.so.0
ELF     7e9b8000-7e9c6000       Deferred        libbrotlidec.so.1
ELF     7e9c6000-7eae8000       Deferred        libharfbuzz.so.0
ELF     7eae8000-7eb02000       Deferred        libz.so.1
ELF     7eb02000-7eb41000       Deferred        libpng16.so.16
ELF     7eb41000-7eb54000       Deferred        libbz2.so.1
ELF     7eb54000-7ec22000       Deferred        libfreetype.so.6
ELF     7ec30000-7eda8000       Deferred        win32u.so
ELF     f7afd000-f7bd0000       Deferred        libm.so.6
ELF     f7bd0000-f7c9c000       Export          ntdll.so
ELF     f7d9c000-f7f8d000       Deferred        libc.so.6
ELF     f7f9d000-f7fd2000       Deferred        ld-linux.so.2
ELF     f7fd2000-f7fd7000       Deferred        <wine-loader>
Threads:
process  tid      prio    name (all IDs are in hex)
00000038 services.exe
	0000003c    0     
	00000040    0     wine_rpcrt4_server
	0000004c    0     wine_rpcrt4_io
	0000005c    0     wine_rpcrt4_io
	00000080    0     wine_rpcrt4_io
	000000b4    0     wine_rpcrt4_io
	000000d4    0     wine_rpcrt4_io
	000000ec    0     
	000000f8    0     wine_rpcrt4_io
00000044 winedevice.exe
	00000048    0     
	00000054    0     
	00000058    0     wine_sechost_service
	00000060    0     
	0000006c    0     
	00000074    0     
	000000e4    0     
	000000e8    0     
00000064 explorer.exe
	00000068    0     
	000000b0    0     
	000000cc    0     wine_rpcrt4_server
00000078 winedevice.exe
	0000007c    0     
	00000084    0     
	00000088    0     wine_sechost_service
	0000008c    0     
	00000090    0     
	00000094    0     
	00000098    0     
	000000a0    0     
	000000ac    0     
000000a4 plugplay.exe
	000000a8    0     
	000000b8    0     
	000000bc    0     wine_sechost_service
	000000c0    0     wine_rpcrt4_server
	00000320    0     wine_rpcrt4_io
	00000324    0     wine_threadpool_worker
000000c4 svchost.exe
	000000c8    0     
	000000dc    0     
	000000e0    0     wine_sechost_service
000000f0 rpcss.exe
	000000f4    0     
	000000fc    0     
	00000100    0     wine_sechost_service
	00000104    0     wine_rpcrt4_server
	00000108    0     wine_rpcrt4_server
	0000010c    0     wine_rpcrt4_io
	00000510    0     wine_rpcrt4_io
	00000730    0     wine_rpcrt4_io
	000007a8    0     wine_rpcrt4_io
00000114 WeChat.exe
	00000118    0     
	00000120    0     Flush another mapping thread
	00000124    0     
	00000128    0     
	0000012c    0     MMMojo IO Thread
	00000130    0     BrokerEvent
	00000134    0     ThreadPoolServiceThread
	00000138    0     ThreadPoolForegroundWorker
	0000013c   -2     ThreadPoolBackgroundWorker
	00000140    0     MMMojo IPC Thread
	00000170    0     TaskSchedulerServiceThread
	00000174   -2     TaskSchedulerWeChatWinBackgroundWorker
	00000178   -2     TaskSchedulerWeChatWinBackgroundBlockingWorker
	0000017c    0     TaskSchedulerWeChatWinForegroundWorker
	00000180    0     TaskSchedulerWeChatWinForegroundBlockingWorker
	00000184    0     
	00000188    0     
	0000018c    0     
	00000190    0     
	00000194    0     
	00000198    0     
	0000019c    0     
	000001a4    0     
	000001a8    0     andromeda::quic::recycle
	000001ac    0     andromeda::quic::timeout-guard
	000001b0    0     andromeda::quic::proxy
	000001b4    0     
	000001b8    0     
	000001bc    0     
	000001cc    0     
	000001d4    0     
	000001e8    0     
	000001ec    0     xplugin_init_thread
	000001f0    0     
	000001f4    0     
	000001f8    0     
	000001fc    0     
	00000200    0     
	00000204    0     xplugin_manager_plugin
	00000208    0     
	0000020c    0     
	00000210    0     
	00000214    0     
	00000218    0     
	0000021c    0     
	00000220    0     
	00000224    0     
	00000228    0     
	0000022c    0     
	00000230    0     
	00000234    0     
	00000238    0     
	0000023c    0     
	0000025c    0     task_thread
	00000264    0     xlog_thread
	0000026c    0     wechat_browser_io_thread
	00000270    0     webview_io_thread
	00000290    0     applet_io_thread
	000003d4    0     
	000003e4    0     
	000003e8    0     
	000003ec    0     
	00000408    0     
	0000046c    0     
	00000470    0     
	0000048c    0     MMMojo RW Thread 7092099748123932724
	00000494    0     MMMojo RW Sync Thread 7092099748123932724
	00000498    0     ThreadPoolSingleThreadForegroundBlocking0
	000004a4    0     MMMojo RW Thread 783027012604522418
	000004ac    0     MMMojo RW Sync Thread 783027012604522418
	000004b4    0     MMMojo RW Thread 5471431939808437428
	000004b8    0     wine_rpcrt4_server
	000004bc    0     MMMojo RW Sync Thread 5471431939808437428
	0000051c    0     
	00000520    0     
	000007f4    0     callback_thread_
	00000a3c    0     
	00000974    0     
	00000c80    0     
	00000c84    0     
	00000c88    0     
	00000c8c    0     
	00000c90    0     
	00000c94    0     
	00000c98    0     
	00000c9c    0     
	00000ca0    0     
	00000ca4    0     
	00000cac    0     
	00000cb4    0     
	00000cb8    0     
	00000cc4    0     
	00000ccc    0     
	00000cdc    0     
	00000ce0    0     
	00000ce8    0     
	00000cf4    0     
	00000cfc    0     
	00000d24    0     
	00000d28    0     
	00000d2c    0     
	00000d30    0     
	00000d34    0     
	00000d38    0     
	00000d3c    0     
	00000d40    0     
	00000d44    0     
	00000d48    0     
	00000d4c    0     
	00000d50    0     
	00000d5c    0     
	00000d64    0     
	00000d6c    0     
	00000d74    0     
	00000d7c    0     
	00000d8c    0     
	00000d94    0     
	00000d98    0     
	00000d9c    0     
	00000da4    0     
	00000da8    0     
	00000db0    0     
	00000db4    0     
	00000dbc    0     
	00000dc8    0     
	00000dd0    0     
	00000dd8    0     
	00000de8    0     
	00000dec    0     
	00000df0    0     
	00000e00    0     
	00000e04    0     
	00000e08    0     
	00000e0c    0     
	00000e10    0     
	00000e14    0     
	00000e18    0     
	00000e1c    0     
	00000e20    0     
	00000e24    0     
	00000e28    0     
	00000e2c    0     
	00000e30    0     
	00000e34    0     
	00000e38    0     
	00000e3c    0     
	00000e40    0     
00000144 mmcrashpad_handler64.exe
	00000148    0     
	0000014c    0     
	00000150    0     upload_log_thread_WECHAT
	00000154    0     slave_upload_log_thread
	00000158    0     
	0000015c    0     
	00000160    0     wine_threadpool_worker
	00000164    0     wine_threadpool_waitqueue
	00000168    0     
	0000016c    0     
00000274 WeChatAppEx.exe
	00000278    1     CrBrowserMain
	000002c8    0     BrokerEvent
	000002cc    0     xlog_thread
	000002d0    0     ThreadPoolServiceThread
	000002d4    0     ThreadPoolForegroundWorker
	000002d8   -2     ThreadPoolBackgroundWorker
	000002dc    0     ThreadPoolForegroundWorker
	000002e0    0     ThreadPoolForegroundWorker
	000002e4    1     Chrome_IOThread
	000002e8    0     MemoryInfra
	000002ec    0     wine_threadpool_worker
	000002f0    0     wine_threadpool_waitqueue
	000002f4    0     ThreadPoolSingleThreadCOMSTASharedForeground0
	000002f8    0     ThreadPoolForegroundWorker
	000002fc    0     ThreadPoolSingleThreadForegroundBlocking1
	00000300    0     ThreadPoolForegroundWorker
	00000304    0     CompositorTileWorker1
	00000308    0     AudioThread
	00000314    0     wine_mmdevapi_notification
	00000318    0     wine_sechost_device_notify
	0000031c    0     VideoCaptureThread
	00000330   -2     ThreadPoolSingleThreadSharedBackgroundBlocking2
	00000334    0     ipc_thread
	00000338    0     process_watcher
	0000033c   -2     ThreadPoolBackgroundWorker
	00000474    0     ThreadPoolSingleThreadSharedForeground3
	00000478    0     ThreadPoolForegroundWorker
	0000047c    0     ThreadPoolForegroundWorker
	00000508    0     ThreadPoolSingleThreadCOMSTASharedForegroundBlocking4
	0000050c    0     wine_rpcrt4_server
	00000530    0     ThreadPoolForegroundWorker
	00000534    0     ThreadPoolForegroundWorker
	000005ec    0     CacheThread_BlockFile
	00000840    0     wmpf_db_thread
00000298 WeChatAppEx.exe
	0000029c    0     CrashpadMainThread
	000002a4    0     
	000002a8    0     upload_log_thread_browser
	000002ac    0     slave_upload_log_thread
	000002b0    0     
	000002b4    0     
	000002b8    0     wine_threadpool_worker
	000002bc    0     wine_threadpool_waitqueue
	000002c0    0     
	000002c4    0     
0000030c WeChatAppEx.exe
	00000310    0     network.CrUtilityMain
	00000344    0     BrokerEvent
	00000348    0     ThreadPoolServiceThread
	0000034c    0     ThreadPoolForegroundWorker
	00000350   -2     ThreadPoolBackgroundWorker
	00000354    0     Chrome_ChildIOThread
	00000358    0     ThreadPoolForegroundWorker
	0000035c    0     wine_threadpool_worker
	00000360    0     wine_threadpool_waitqueue
	00000364    0     ThreadPoolForegroundWorker
	00000368    0     ThreadPoolForegroundWorker
	0000036c    0     ThreadPoolForegroundWorker
	00000518   -2     ThreadPoolBackgroundWorker
	000006a0    0     ThreadPoolForegroundWorker
	000006a4    0     ThreadPoolForegroundWorker
	000006a8    0     ThreadPoolForegroundWorker
00000328 WeChatAppEx.exe
	0000032c    1     CrGpuMain
	00000374    0     GpuWatchdog
	00000384    0     dxvk-submit
	00000388    0     dxvk-queue
	0000038c    0     dxvk-cs
	00000390    0     ThreadPoolServiceThread
	00000394    0     ThreadPoolForegroundWorker
	00000398   -2     ThreadPoolBackgroundWorker
	0000039c    1     Chrome_ChildIOThread
	000003a0    0     wine_threadpool_worker
	000003a4    0     ThreadPoolForegroundWorker
	000003a8    0     wine_threadpool_waitqueue
	000003ac    1     VizCompositorThread
000004d0 WeChatPlayer.exe
	000004d4    0     
	000005f0    0     
	000005f8    0     
	00000600    0     MMMojo IO Thread
	00000610    0     BrokerEvent
	00000618    0     ThreadPoolServiceThread
	00000620    0     ThreadPoolForegroundWorker
	00000628   -2     ThreadPoolBackgroundWorker
	00000630    0     MMMojo IPC Thread
	0000063c    0     MMMojo RW Thread 8804574328866126969
	00000640    0     MMMojo RW Sync Thread 8804574328866126969
	000006f4    0     
000004ec WechatUtility.exe
	000004f0    0     
	0000054c    0     MMMojo IO Thread
	00000550    0     BrokerEvent
	00000554    0     ThreadPoolServiceThread
	00000558    0     ThreadPoolForegroundWorker
	0000055c   -2     ThreadPoolBackgroundWorker
	00000564    0     MMMojo IPC Thread
	00000568    0     TaskSchedulerServiceThread
	0000056c   -2     TaskSchedulerUtilityThreadPoolBackgroundWorker
	00000570   -2     TaskSchedulerUtilityThreadPoolBackgroundBlockingWorker
	00000574    0     TaskSchedulerUtilityThreadPoolForegroundWorker
	00000578    0     TaskSchedulerUtilityThreadPoolForegroundBlockingWorker
	0000057c    0     SCANQRThread
	00000580    0     SCANTextThread
	00000584    0     MMMojo RW Thread 336054568709586980
	00000588    0     MMMojo RW Sync Thread 336054568709586980
	000005a0    0     
	000005a4    0     
	000005a8    0     
	000005ac    0     
	000005b0    0     
	000005b4    0     
	000005b8    0     
	000005bc    0     
	000005c0    0     
	000005c4    0     
	000005c8    0     
	000005cc    0     
	000005d0    0     
	000005d4    0     
	000005d8    0     
	000005dc    0     
	000005e0    0     
	000005e4    0     
	000005e8    0     
000004fc WeChatOCR.exe
	00000500    0     
	000005f4    0     MMMojo IO Thread
	000005fc    0     BrokerEvent
	00000604    0     ThreadPoolServiceThread
	00000608    0     ThreadPoolForegroundWorker
	0000060c   -2     ThreadPoolBackgroundWorker
	00000614    0     MMMojo IPC Thread
	0000061c    0     TaskSchedulerServiceThread
	00000624   -2     TaskSchedulerOCRThreadPoolBackgroundWorker
	0000062c   -2     TaskSchedulerOCRThreadPoolBackgroundBlockingWorker
	00000634    0     TaskSchedulerOCRThreadPoolForegroundWorker
	00000638    0     TaskSchedulerOCRThreadPoolForegroundBlockingWorker
	00000644    0     
	00000648    0     
	0000064c    0     
	00000650    0     
	00000654    0     
	00000658    0     
	0000065c    0     
	00000660    0     
	00000664    0     
	00000668    0     
	0000066c    0     
	00000670    0     
	00000674    0     
	00000678    0     
	0000067c    0     
	00000680    0     
	00000684    0     
	00000688    0     
	0000068c    0     
	00000698    0     MMMojo RW Thread 7511897208961813886
	0000069c    0     MMMojo RW Sync Thread 7511897208961813886
00000544 WeChatAppEx.exe
	00000548    0     flue.CrUtilityMain
	000006c8    0     BrokerEvent
	000006d0    0     xlog_thread
	000006d4    0     ThreadPoolServiceThread
	000006e0    0     ThreadPoolForegroundWorker
	000006e4   -2     ThreadPoolBackgroundWorker
	000006ec    0     Chrome_ChildIOThread
	000006f0    0     ThreadPoolForegroundWorker
	000006f8    0     
	000006fc    0     
	00000700    0     
	00000704    0     
	00000708    0     
	0000070c    0     
	00000710    0     
	00000714    0     sqlite thread
00000690 WeChatAppEx.exe
	00000694    1     CrRendererMain
	0000075c    0     ThreadPoolServiceThread
	00000760    0     ThreadPoolForegroundWorker
	00000764   -2     ThreadPoolBackgroundWorker
	00000768    1     Chrome_ChildIOThread
	0000076c    0     ThreadPoolForegroundWorker
	00000770    0     wine_threadpool_worker
	00000778    0     wine_threadpool_waitqueue
	0000077c    0     GpuMemoryThread
	000007c8    1     Compositor
	000007cc    0     ThreadPoolSingleThreadSharedForegroundBlocking0
	00000970    0     ThreadPoolForegroundWorker
	000009a0    0     ThreadPoolForegroundWorker
	000009a4    0     ThreadPoolForegroundWorker
	0000093c    0     ThreadPoolForegroundWorker
	00000950    0     ThreadPoolForegroundWorker
	00000aa0    0     ThreadPoolForegroundWorker
	00000ac4    0     ThreadPoolForegroundWorker
	00000aa8    0     ThreadPoolForegroundWorker
	00000aac    0     ThreadPoolForegroundWorker
	00000ab0    0     ThreadPoolForegroundWorker
	00000ab4    0     ThreadPoolForegroundWorker
	00000abc    0     ThreadPoolForegroundWorker
	00000c7c   -2     ThreadPoolBackgroundWorker
000006d8 WeChatAppEx.exe
	000006dc    1     CrRendererMain
	0000073c    0     ThreadPoolServiceThread
	00000740    0     ThreadPoolForegroundWorker
	00000744   -2     ThreadPoolBackgroundWorker
	00000748    1     Chrome_ChildIOThread
	0000074c    0     ThreadPoolForegroundWorker
	00000750    0     wine_threadpool_worker
	00000754    0     wine_threadpool_waitqueue
	00000758    0     GpuMemoryThread
	000007b4    1     Compositor
	000007b8    0     ThreadPoolSingleThreadSharedForegroundBlocking0
	000007c4    0     ThreadPoolForegroundWorker
	0000082c    0     ThreadPoolForegroundWorker
	000007d4    0     ThreadPoolForegroundWorker
	00000954    0     ThreadPoolForegroundWorker
	000007d8    0     ThreadPoolForegroundWorker
	000007e8    0     ThreadPoolForegroundWorker
	000007ec    0     ThreadPoolForegroundWorker
	000007e0    0     ThreadPoolForegroundWorker
	00000830    0     ThreadPoolForegroundWorker
	00000a20    0     ThreadPoolForegroundWorker
	00000734   -2     ThreadPoolBackgroundWorker
00000718 explorer.exe
	0000071c    0     
	00000728    0     
	0000072c    0     wine_rpcrt4_server
00000720 WeChatAppEx.exe
	00000724    1     CrRendererMain
	00000780    0     ThreadPoolServiceThread
	00000784    0     ThreadPoolForegroundWorker
	00000788   -2     ThreadPoolBackgroundWorker
	0000078c    1     Chrome_ChildIOThread
	00000790    0     ThreadPoolForegroundWorker
	00000794    0     wine_threadpool_worker
	00000798    0     wine_threadpool_waitqueue
	0000079c    0     GpuMemoryThread
	000007bc    1     Compositor
	000007c0    0     ThreadPoolSingleThreadSharedForegroundBlocking0
	0000081c    0     DedicatedWorker thread
	00000820    0     
	00000824    0     ThreadPoolForegroundWorker
	00000828    0     ThreadPoolSingleThreadSharedForeground1
	0000094c    0     ThreadPoolForegroundWorker
	000007e4    0     ThreadPoolForegroundWorker
	000007dc    0     ThreadPoolForegroundWorker
	000007d0    0     ThreadPoolForegroundWorker
	000007f0    0     ThreadPoolForegroundWorker
0000084c WeChatAppEx.exe
	00000850    1     CrRendererMain
	00000860    0     ThreadPoolServiceThread
	00000864    0     ThreadPoolForegroundWorker
	00000868   -2     ThreadPoolBackgroundWorker
	0000086c    1     Chrome_ChildIOThread
	00000870    0     ThreadPoolForegroundWorker
	00000874    0     wine_threadpool_worker
	00000878    0     wine_threadpool_waitqueue
	0000087c    0     GpuMemoryThread
	00000880    1     Compositor
	00000884    0     ThreadPoolSingleThreadSharedForegroundBlocking0
	00000888    0     
	0000088c    0     ThreadPoolForegroundWorker
	00000890    0     ThreadPoolForegroundWorker
	00000894    0     
	00000898    0     ThreadPoolForegroundWorker
	0000089c    0     ThreadPoolForegroundWorker
	000008a8    0     ThreadPoolForegroundWorker
	000008ac    0     ThreadPoolForegroundWorker
	000008c8    0     ThreadPoolForegroundWorker
	000008cc    0     ThreadPoolForegroundWorker
	000008d0    0     ThreadPoolForegroundWorker
	000008d4    0     ThreadPoolForegroundWorker
	00000844   -2     ThreadPoolBackgroundWorker
00000958 WeChatAppEx.exe
	0000095c    1     CrRendererMain
	00000980    0     ThreadPoolServiceThread
	00000984    0     ThreadPoolForegroundWorker
	00000988   -2     ThreadPoolBackgroundWorker
	0000098c    1     Chrome_ChildIOThread
	00000990    0     ThreadPoolForegroundWorker
	00000994    0     wine_threadpool_worker
	00000998    0     wine_threadpool_waitqueue
	0000099c    0     GpuMemoryThread
	000009f8    1     Compositor
	000009fc    0     ThreadPoolSingleThreadSharedForegroundBlocking0
000008f0 (D) Z:\root\res\install\python-3.12.6-amd64.exe
	["Z:\root\res\install\python-3.12.6-amd64.exe" ]
	000008ec    0 <== 
	00000920    0     
000008f8 conhost.exe
	000008fc    0     
00000924 explorer.exe
	00000928    0     
	000007a4    0     
	0000092c    0     wine_rpcrt4_server
System information:
    Wine build: wine-9.1 (Staging)
    Platform: x86_64 (guest: i386)
    Version: Windows 10
    Host system: Linux
    Host version: 5.15.153.1-microsoft-standard-WSL2

**Comment by danni-cool** [comment]
wine这块不太能解答，尝试在纯x86架构上换尽量新的linux版本
https://github.com/danni-cool/wechatbot-provider-windows?tab=readme-ov-file#qa

**Comment by danni-cool** [comment]
试下最新版，我已经build-in python3 和 wechat 环境了
