### ISSUE TITLE
./start.sh: line 5:  1142 Segmentation fault

### ISSUE THREAD

**Issue by strongFn** [danni-cool/wechatbotKit-py-http#5]
![微信图片_20241125192845](https://github.com/user-attachments/assets/a16761f4-4b3c-4fc9-b6f8-a686e1a7b2fe)

**Comment by strongFn** [comment]
![微信图片_20241125150323](https://github.com/user-attachments/assets/fad9f74a-4f0c-400b-b12e-a037164d8e3e)
进入桌面报这个错误，然后显示无网络，点击StartService执行无反应

**Comment by strongFn** [comment]
![微信图片_20241125202207](https://github.com/user-attachments/assets/3f4bf7d3-dd34-4a46-bbcf-5daf6baafd11)

**Comment by danni-cool** [comment]
看你在原作者那边issue提问已经解决了，我就关了，留个备份 https://github.com/Saroth/docker_wechat/issues/4
