### ISSUE TITLE
SDK 初始化错误

### ISSUE THREAD

**Issue by liangkuosec** [danni-cool/wechatbotKit-py-http#7]
## 宿主机环境：

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian

## 容器日志：

xrdp-sesexec[38]: [INFO ] Starting X server on display 12: Xvnc :12 -auth .Xauthority -geometry 1920x1080 -depth 32 -rfbauth /root/.vnc/sesman_passwd-root@142d36fbd436:12 -bs -nolisten tcp -localhost -dpi 96 

xrdp-sesexec[37]: [INFO ] X server :12 is working

xrdp-sesexec[37]: [INFO ] Starting window manager for display :12

xrdp-sesexec[37]: [INFO ] Starting the xrdp channel server for display :12

xrdp-sesexec[42]: [INFO ] Using the default window manager on display 12: /usr/libexec/xrdp/startwm-bash.sh

xrdp-sesexec[37]: [INFO ] Session in progress on display :12. Waiting until the window manager (pid 42) exits to end the session

xrdp[35]: [INFO ] xrdp_wm_log_msg: session is available on display 12 for user root

xrdp[35]: [INFO ] xrdp_wm_log_msg: Connecting to session

xrdp[35]: [INFO ] loaded module 'libvnc.so' ok, interface size 4832, version 4

xrdp[35]: [INFO ] VNC: Clipboard (if available) is provided by chansrv facility

xrdp[35]: [INFO ] xrdp_wm_log_msg: Connecting to chansrv

xrdp-chansrv[43]: [INFO ] Socket 14: connection accepted from AF_UNIX

xrdp[35]: [INFO ] Layout from ClientLayout (geom=1920x1080 #screens=1) : 0:(1920x1080+0+0)

xrdp[35]: [INFO ] Layout from OldServerLayout (geom=1920x1080 #screens=1) : 1804289383:(1920x1080+0+0)

xrdp-chansrv[43]: [INFO ] sound_process_output_format:

xrdp-chansrv[43]: [INFO ]       wFormatNo       0

xrdp-chansrv[43]: [INFO ]       wFormatTag      WAVE_FORMAT_PCM

xrdp-chansrv[43]: [INFO ]       nChannels       2

xrdp-chansrv[43]: [INFO ]       nSamplesPerSec  44100

xrdp-chansrv[43]: [INFO ]       nAvgBytesPerSec 176400

xrdp-chansrv[43]: [INFO ]       nBlockAlign     4

xrdp-chansrv[43]: [INFO ]       wBitsPerSample  16

xrdp-chansrv[43]: [INFO ]       cbSize          0

xrdp-chansrv[43]: [INFO ] sound_process_output_format:

xrdp-chansrv[43]: [INFO ]       wFormatNo       1

xrdp-chansrv[43]: [INFO ]       wFormatTag      WAVE_FORMAT_PCM

xrdp-chansrv[43]: [INFO ]       nChannels       2

xrdp-chansrv[43]: [INFO ]       nSamplesPerSec  22050

xrdp-chansrv[43]: [INFO ]       nAvgBytesPerSec 88200

xrdp-chansrv[43]: [INFO ]       nBlockAlign     4

xrdp-chansrv[43]: [INFO ]       wBitsPerSample  16

xrdp-chansrv[43]: [INFO ]       cbSize          0

xrdp-chansrv[43]: [INFO ] sound_process_training: round trip time 16

xrdp-chansrv[43]: [INFO ] Detected remote smartcard 'SCARD'

xrdp-chansrv[43]: [INFO ] Detected remote printer 'PRN4' (not supported)

xrdp-chansrv[43]: [INFO ] Detected remote printer 'PRN3' (not supported)

xrdp-chansrv[43]: [INFO ] Detected remote printer 'PRN2' (not supported)

xrdp-chansrv[43]: [ERROR] clipboard_event_selection_request: unknown target text/plain;charset=utf-8

xrdp-chansrv[43]: [ERROR] clipboard_event_selection_request: unknown target text/plain;charset=utf-8

xrdp-chansrv[43]: [ERROR] clipboard_event_selection_request: unknown target COMPOUND_TEXT

xrdp-chansrv[43]: [ERROR] clipboard_event_selection_request: unknown target text/plain;charset=utf-8

xrdp-chansrv[43]: [ERROR] clipboard_event_selection_request: unknown target COMPOUND_TEXT

xrdp-chansrv[43]: [ERROR] clipboard_event_selection_request: unknown target text/plain;charset=utf-8

xrdp-chansrv[43]: [ERROR] clipboard_event_selection_request: unknown target COMPOUND_TEXT

xrdp-chansrv[43]: [ERROR] clipboard_event_selection_request: unknown target text/plain;charset=utf-8

xrdp-chansrv[43]: [ERROR] clipboard_event_selection_request: unknown target text/plain;charset=utf-8

xrdp-chansrv[43]: [ERROR] clipboard_c2s_in_files: Bad number of files in list (4784219)

## 问题截图：

![image](https://github.com/user-attachments/assets/b06db475-f75f-46fa-aaa7-5134bd39c32d)

**Comment by liangkuosec** [comment]
弹窗应该也是提示中文错误信息

**Comment by strongFn** [comment]
我也是这个问题，请问解决了吗？

**Comment by danni-cool** [comment]
修了一个权限问题，在windows平台构建了版本推送了，再拉下试试
